// <auto-generated />
namespace EF_Code_First_Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class databasetablecreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databasetablecreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202211160436064_databasetable creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
